In [39]:
import numpy as np
import matplotlib.pyplot as plt

In [40]:
class Layer:
    def __init__(self):
        self.x = None
        self.y = None
    
    def forward(self, x):
        pass

    def backward(self, gradient, lr=0.01):
        pass

In [41]:
class LinearLayer(Layer):
    
    def __init__(self, x_size, y_size):
        self.weights = np.random.rand(y_size, x_size)
        self.bias = np.random.rand(y_size, 1)
    
    def forward(self,x):
        self.x = x
        return np.dot(self.weights, self.x.T) + self.bias
    
    def backward(self,x,w):
        return x
    
        

In [65]:
# Define XOR inputs -- prepend a constant of 1 for bias multiplication
samples = np.array([[0, 0],
                    [0, 1],
                    [1, 0],
                    [1, 1]])
targets = np.array([0, 1, 1, 0])

'''fig = plt.figure()
ax = fig.add_subplot(111)
ax.scatter(samples[:, 0], samples[:, 1], c=targets)'''

'fig = plt.figure()\nax = fig.add_subplot(111)\nax.scatter(samples[:, 0], samples[:, 1], c=targets)'

In [71]:
n1 = LinearLayer(2,4)
y = n1.forward(samples)
print(y)

[[0.12199185 0.55140012 1.07661201 1.50602027]
 [0.3127422  1.11205098 1.04152129 1.84083008]
 [0.16582697 0.44670899 0.79511929 1.0760013 ]
 [0.82751767 1.07960597 1.5786696  1.8307579 ]]


In [72]:
n1.bias

array([[0.12199185],
       [0.3127422 ],
       [0.16582697],
       [0.82751767]])

In [73]:
n1.weights


array([[0.95462016, 0.42940826],
       [0.7287791 , 0.79930878],
       [0.62929231, 0.28088201],
       [0.75115193, 0.2520883 ]])

In [74]:
n1.x

array([[0, 0],
       [0, 1],
       [1, 0],
       [1, 1]])